### ISSUE TITLE
OWIE  - Overridden SOC never under 5%

### ISSUE THREAD

**Issue by wheelerone** [lolwheel/Owie#26]
Hi, Onewheel Pint (5314 - Gemini 5050) with Quart Battery will never Captain Morgan (low battery). 
Lowest Overridden SOC is 5%, what should i do?
Regards

![owie](https://user-images.githubusercontent.com/101931996/159121550-3d9c9250-3501-4d89-a42b-9aa83ce0f97f.PNG)

**Comment by lolwheel** [comment]
Yeah just ate it myself because of this, fixing.

**Comment by lolwheel** [comment]
Fixed.

**Comment by dmimwheel** [comment]
perfect, 5 % floor fixed! Light bar still yellow, not going red at low volatge and no captain morgan :/

**Comment by lolwheel** [comment]
OK thanks for the feedback. I think I have an idea what's going on, it's just that I'm not sure I'll be able to fix it and this isn't too high up on my priority list.

I'm fairly confident that the "battery empty" flag is part of the status message (message code 0) which I am swallowing completely to circumvent the range limitation on the newer boards. I need to figure out which flag in the status byte does indeed correspond to this state and let a packet through when I see this flag set.

For this I'll have to run the board battery into the ground and I'm sorta lazy to do that.

If you guys end up in that situation, you can help me out by opening the Owie web config page, hit "Monitor BMS Data" button and save the first line in the text box which will look something like "ff 55 aa 00 XX 02 YY", the XX or the 5-th byte is the only thing that matters.

Imma reopen this bug, looks like we do have some work to do.

**Comment by wheelerone** [comment]
here is the Monitor BMS Data :)
![IMG_9223](https://user-images.githubusercontent.com/101931996/159571420-daa81152-2ed4-4efe-bb8b-f87c1b7b0d01.jpg)

**Comment by lolwheel** [comment]
Yay teamwork! Never seen the 0x4 flag appear before, just tried injecting it and tadaa, got the pushback and "Needs juice" notification in the app, that was it!

Submitting the fix in a sec.
