### ISSUE TITLE
Pint X support?

### ISSUE THREAD

**Issue by carltronic** [lolwheel/Owie#28]
Will this work on the Pint X? I just really want to see the cell voltages.
Thanks.

**Comment by lolwheel** [comment]
You will see The cell voltages in the Owie status page.

-------- Original Message --------

**Comment by carltronic** [comment]
Thanks. I see in the README that it works on Pints, but is it also good for the Pint X?

**Comment by lolwheel** [comment]
The battery expansion capability is untested on Pint X. I've heard rumors that it doesn't work.

-------- Original Message --------
