### ISSUE TITLE
LED support?

### ISSUE THREAD

**Issue by matzZz** [lolwheel/Owie#31]
Hi,
is it possible that you add support for battery level shown on a Adafruit NeoPixel Stick (Like Pint/GT status light)?

**Comment by lolwheel** [comment]
It'd be pretty hard as ws2812b lights require tight timing for updates and esp8266 doesn't have a dedicated pwm so I wanna say no.

-------- Original Message --------

**Comment by matzZz** [comment]
A led like this should work…
http://www.esp8266learning.com/some-neopixel-examples.php

**Comment by ow-breaker** [comment]
It's probably possible using the FASTLED library, however you have to be
extremely cognizant of how long it'll take to write the data to the LEDs as
that can be a point of potential issues.
I'm unsure of what board you're planning to do this on, but you'll have to
run some wires out of the battery box, which requires pretty serious
modification and forethought.

**Comment by lolwheel** [comment]
This isn't viable, closing the issue.
