### ISSUE TITLE
Did not charge

### ISSUE THREAD

**Issue by matzZz** [lolwheel/Owie#37]
since i installed owie…
if i take a x minute break while a ride the app thinks i'm charging the Onewheel.

![E185907C-F074-423D-B203-FD3BA1019A43](https://user-images.githubusercontent.com/12873902/167742294-7ddfab47-a937-44ed-a903-54fcd39a83d8.jpeg)

![DE6A9A54-202E-44F7-AF88-793728438A63](https://user-images.githubusercontent.com/12873902/167742655-3d2cee4b-c4e7-4277-b9bd-f355cd9ca3d1.jpeg)

**Comment by AnfroneyD** [comment]
When you stop riding, the voltage slowly creeps up and stabilises, it will appear as charging on the app. There's no issue here.

Eg: when riding your voltage would go down to 57v, once you stop putting load on the battery by stopping they will slowly rise back up in voltage. Hence showing charging

**Comment by AnfroneyD** [comment]
It's just the way the owie works, it shows percentage left off voltage, the bms appears to show battery remaining as Amp Hours used,

That's why it fluctuates up and down as you ride

**Comment by lolwheel** [comment]
@AnfroneyD is correct. This is just an artifact of Owie using only voltage to guesstimate the charge state.
