### ISSUE TITLE
overcharge warning and shutoff

### ISSUE THREAD

**Issue by rgalverson** [lolwheel/Owie#38]
It seems like Owie is swallowing the overcharge warning and shutoff alerts from the BMS to the Main controller.  I live at the top of a hill and *always* got both before I wasted enough battery to have room for downhill charging, before I put in Owie.  Now I never get them.  I did capture an Owie status with an 08 in the status byte ("ff 55 aa 00 08 02 06").  I tried adding a line to the packet parser to pass that status through, and I did get an overcharge shutoff.  Maybe there is another bit for the warning?

![Screenshot_20220503-165647](https://user-images.githubusercontent.com/61577265/167767041-f01e7643-4aa4-4ff9-ad40-34a27d2fd6a4.png)

**Comment by lolwheel** [comment]
Fixed.
