### ISSUE TITLE
BMS reports 0%, Overridden SOC reports 67%, and the Battery has 56.88v, but the board won't let me ride

### ISSUE THREAD

**Issue by an-d-uu** [lolwheel/Owie#45]
I am trying to diagnose this issue and will include a screenshot. Basically the BMS reports 0% which after a few seconds shuts the board down even though the battery voltage is at 56.88v. Where should I be looking to find the issue?

![Onewheel_OWIE_BMS_0](https://user-images.githubusercontent.com/39595991/172021873-0ae38706-9ede-4d27-b473-810489a393e1.jpg)

Forgot to mention that I had this on the charger and had both the BMS and SOC reporting above 95%. I was able to ride the board and was not seeing any issues until a mile or two into the ride.

**Comment by an-d-uu** [comment]
After I posted this I saw issue #29 and am in the process of charging this to 100%, will report back if it does it again once it's finished charging.

**Comment by lolwheel** [comment]
what hw revision of the board? the reported soc should have nothing to do with shutting off. likely that's your BMS acting up

-------- Original Message --------

**Comment by lolwheel** [comment]
oh one of your cells is wrecked. the voltage is at 2.4v

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by an-d-uu** [comment]
![image](https://user-images.githubusercontent.com/39595991/172022737-e22a8b15-5a86-45ea-9d3c-cf7925b4701f.jpeg)

Here is a shot of the diagnostics page.

**Comment by an-d-uu** [comment]
So it has been charging for an hour and the BMS is now reporting 100%, that one cell is still off. Here is a current screen shot. Going to take it for a ride and see how long before it runs out.

<img width="427" alt="Screen Shot 2022-06-04 at 3 10 31 PM" src="https://user-images.githubusercontent.com/39595991/172024131-b80bffd8-85cb-4ce7-ba8c-f5c926d16191.png">

**Comment by lolwheel** [comment]
you need a new battery pack, that's a huge difference in voltages

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by an-d-uu** [comment]
Ok will look at getting a new one, thanks for all your help!

**Comment by an-d-uu** [comment]
So after charging the BMS turned the board off at 67% again, so I will take the thing apart make sure all of the soldering points are good and look at getting a new main battery.

<img width="427" alt="Screen Shot 2022-06-04 at 3 42 48 PM" src="https://user-images.githubusercontent.com/39595991/172024979-f9311e22-0a86-4552-8b72-6acbd0c5eac8.png">

As soon as I plugged it in it reports 72%, so I am wondering if the GT40 I purchased as an external battery pack is causing issues. I will go ahead and close this issue.

**Comment by lolwheel** [comment]
This isn't the place to debug the issue, pop into Onewheel discord, a lot of handy people hang in the modding thread. If you haven't had an issue with the battery before, you might have shorted the balancing circuit for the cell while tinkering with the board. That big of a difference in cell voltages is pretty wild

-------- Original Message --------

**Comment by an-d-uu** [comment]
Will do, this is the first time I have had issues and was actually wondering how I could debug it.
