### ISSUE TITLE
Why is the ESP WebTools page ow-breaker not recommended atm? worked for me

### ISSUE THREAD

**Issue by haemse** [lolwheel/Owie#48]
Why is the ESP WebTools page ow-breaker not recommended atm?

worked for me

thou v0.0.1

is it recommended to use 1.1.0
?

**Comment by lolwheel** [comment]
The only issue is that `ow-breaker`'s page isn't automatically updated with the new releases. It's a third-party page that I'm not in control of.

My recommendation is to always use the latest official release on Owie's page so yes, in this situation you'd have to download it manually and perform the first install using `esptool` or other ESP8266 flashing method.
