### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by thibauddavid** [lolwheel/Owie#5]
Hi !

I see that you just changed your project's name from `ow_bms_mitm` to `OWEnhancer`
However, this is already the name of my iOS Cydia tweak [OnewheelEnhancer](https://github.com/thibauddavid/onewheelenhancer-issues).

Would you mind finding another name which would avoid any confusion between both our projects ?

Thanks

**Comment by lolwheel** [comment]
Renamed to Owie.
