### ISSUE TITLE
Quart battery %

### ISSUE THREAD

**Issue by SkaFazz** [lolwheel/Owie#51]
A fully charged Pint with Chi Quart is reading 94%. 
All cells are healthy.

**Comment by JordanVlieg** [comment]
Most likely an issue with the battery.  Can you post a screenshot of the OWIE status screen with the individual cell voltages as well as pack voltage visible?

**Comment by SkaFazz** [comment]
![1060213A-4595-4558-8BC3-6457BB3B230F](https://user-images.githubusercontent.com/102036565/181382583-8b588832-d08a-40ca-87be-204a76b1f1f4.png)

This is what I’m getting after a full charge. Thanks 😊

**Comment by SkaFazz** [comment]
![88858C8B-2A56-4CF9-9144-ECB4C071790F](https://user-images.githubusercontent.com/102036565/181611837-8688a0d8-75cd-45fd-be2b-482008a9cef6.png)

this is after a 2 mile ride from full.

**Comment by lolwheel** [comment]
Yeah need to rewrite battery cell estimation but don't have time.

**Comment by JordanVlieg** [comment]
Unless there is something I am not aware of on the pint where it intentionally doesnt charge to full.  4.14V is not a full battery.  4.2V is full. That battery is indeed 93% full.

**Comment by JordanVlieg** [comment]
This is addressed in https://github.com/lolwheel/Owie/pull/55

**Comment by random1planet** [comment]
Hi, is this issue resolved as I have a owie chip and 63v quart like pint battery, the BMS reported SOC is 100% so wont charge any further but the overridden SOC value is only 90% charged?
