### ISSUE TITLE
OWIE connection issue

### ISSUE THREAD

**Issue by Kikiobi** [lolwheel/Owie#52]
It seems that after setting OWIE to connect to my home Wi-Fi, I can’t seem to connect to OWIE if im out of range of my home Wi-Fi.

**Comment by lolwheel** [comment]
That is a known issue in Arduino core, unfortunately there is no good fix for it for now.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by smit9418** [comment]
my problem is after setting the home network, successfully connecting, then power cycling the board the owie seams to forget the home network. putting it in failsafe AP mode
