### ISSUE TITLE
Wireless Firmware Update Option Missing

### ISSUE THREAD

**Issue by briderx** [lolwheel/Owie#58]
Trying to update to the latest firmware over WiFi, but following the guide, I don't see the "browse" option to upload it.

**Comment by lolwheel** [comment]
You're probably on an old version of Owie. The instructions are up to date for the latest version of owie.

Access the update screen under `/update` URL

**Comment by briderx** [comment]
Thank you! That was exactly the problem! <3

**Comment by Gerlif** [comment]
You might wanna add this to the update instructions.
Both the stable and latest option when flashing for the first time installed a version without the update button.
Had to come here to figure out to put /update in the URL :)
