### ISSUE TITLE
error 23

### ISSUE THREAD

**Issue by ebarraud** [lolwheel/Owie#62]
HELLO,
since July I have an error code 23: Incompatible hardware detected, in the official android application (and on the OW itself by 23 blinks on the power button).
I didn't make any changes on my OW XR....my firmware is 4210....
I tested my battery with OWCE and everything is fine.
I am located in France and with the new air freight rules I cannot return the OW to Future Motion in California. So I'm desperate to find a solution....
It looks like OWIE might be able to help me with my problem. What do you think?
Thanks a lot....

**Comment by lolwheel** [comment]
GitHub issues is used to report errors in Owie code, not as a support forum. Go to the Onewheel discord DIY section for that.
