### ISSUE TITLE
Battery cell voltage to show related cell number to cell voltage read out as well as temp sensors

### ISSUE THREAD

**Issue by Tesurus** [lolwheel/Owie#69]
Would it be possible to add cell voltage indicator rather then just listing them out? same thing with temp sensors

**Comment by Mr-HaleYa** [comment]
Like color code them? Show them Red when low and Green when full?
Could you explain a bit more about what you mean?

**Comment by lolwheel** [comment]
Not sure but also no, this project is pretty much abandoned.
